services:
  api:
    container_name: api
    build:
     context: .
     dockerfile: Dockerfile
    volumes: 
      - .:/app
    ports:
      - "8000:8080"
    restart: always
    depends_on:
      - db

  db:
    container_name: api-db
    image: postgres:latest
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: php-db
