services:
  php:
    container_name: app-api
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: api-db
    image: postgres:latest
    volumes:
     - .docker/dbdata:/var/lib/postgresql/data
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=php-db
