networks:
  my-network:
    driver: bridge

services:
  api:
    container_name: api
    build: .
    volumes: 
      - .:/var/www/html
    ports:
      - "8080:8080"
    expose:
      - 8080
    restart: always
    networks:
      - my-network
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: api-db
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: phpdb
    networks:
      - my-network
